#      _       ____   __  __ 
#     / \     / ___| |  \/  |
#    / _ \   | |     | |\/| |
#   / ___ \  | |___  | |  | |
#  /_/   \_\  \____| |_|  |_|
# The creator of this plugin was fernanACM.
# https://github.com/fernanACM
# ==(CONFIGURATION)==
Settings:
  # ==(WORLD MANAGER)==
  # add to "whitelist" or "blacklist" modes
  WorldManager:
    # Valid modes:
    # - whitelist
    # - blacklist
    # - false
    mode: whitelist
    # Add the names of worlds that are in the whitelist
    worlds-whitelist:
      - "world"
      - "world-2"
      - "ACM"
    # Add the names of worlds that are in the blacklist
    worlds-blacklist:
      - "MinePvP"
      - "ZonePvP"